TOP = ../..
include $(TOP)/configure/CONFIG

#!ARCH = linux-x86
#!ARCH = linux-x86-debug
ARCH = linux-x86_64
#!ARCH = linux-x86_64-debug

TARGETS = envPaths
#TARGETS = envPaths dllPath.bat

include $(TOP)/configure/RULES.ioc
